name: spam_code_package
description: spam_code_package
version: 0.0.1
homepage: https://github.com/TralyFang/spam_code_package
repository: https://github.com/TralyFang/spam_code_package

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
